"""add logged_expiry_at

Revision ID: 196503731df8
Revises: 368261dcbc49
Create Date: 2025-10-22 16:30:01.280481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196503731df8'
down_revision = '368261dcbc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
