"""baseline

Revision ID: 368261dcbc49
Revises: 
Create Date: 2025-10-22 16:09:08.786595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368261dcbc49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=64), nullable=False),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_vin'), 'car', ['vin'], unique=True)
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_car_claim_date', 'claim', ['car_id', 'claim_date'], unique=False)
    op.create_index(op.f('ix_claim_car_id'), 'claim', ['car_id'], unique=False)
    op.create_index(op.f('ix_claim_claim_date'), 'claim', ['claim_date'], unique=False)
    op.create_index(op.f('ix_claim_created_at'), 'claim', ['created_at'], unique=False)
    op.create_table('insurance_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('logged_expiry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policy_car_id'), 'insurance_policy', ['car_id'], unique=False)
    op.create_index(op.f('ix_insurance_policy_end_date'), 'insurance_policy', ['end_date'], unique=False)
    op.create_index(op.f('ix_insurance_policy_start_date'), 'insurance_policy', ['start_date'], unique=False)
    op.create_index('ix_policy_car_end', 'insurance_policy', ['car_id', 'end_date'], unique=False)
    op.create_index('ix_policy_car_start_end', 'insurance_policy', ['car_id', 'start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_car_start_end', table_name='insurance_policy')
    op.drop_index('ix_policy_car_end', table_name='insurance_policy')
    op.drop_index(op.f('ix_insurance_policy_start_date'), table_name='insurance_policy')
    op.drop_index(op.f('ix_insurance_policy_end_date'), table_name='insurance_policy')
    op.drop_index(op.f('ix_insurance_policy_car_id'), table_name='insurance_policy')
    op.drop_table('insurance_policy')
    op.drop_index(op.f('ix_claim_created_at'), table_name='claim')
    op.drop_index(op.f('ix_claim_claim_date'), table_name='claim')
    op.drop_index(op.f('ix_claim_car_id'), table_name='claim')
    op.drop_index('ix_claim_car_claim_date', table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_car_vin'), table_name='car')
    op.drop_table('car')
    op.drop_table('owner')
    # ### end Alembic commands ###
