"""add provider column

Revision ID: d0d526ca60f2
Revises: d1619e7ef742
Create Date: 2025-10-21 14:01:35.216611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d526ca60f2'
down_revision = 'd1619e7ef742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=False))
        batch_op.drop_column('coverage_details')
        batch_op.drop_column('policy_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_number', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('coverage_details', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
